# Utilisez une image de base appropriée
FROM node:14

# Répertoire de travail dans le conteneur
WORKDIR /app

# Copiez les fichiers nécessaires dans le conteneur
COPY package*.json ./

# Installez les dépendances
RUN npm install

# Copiez le reste des fichiers
COPY . .

# Exposez le port sur lequel le service écoute
EXPOSE 80

# Commande pour démarrer le service
CMD ["npm", "start"]
