version: '3.9'

services:
  api:
    build:
      context: ./API
    ports:
      - "3000:3000"
    networks:
      - internal_network
    volumes:
      - ./API/src:/var/www/html  

  thread:
    build:
      context: ./Thread
    ports:
      - "8000:8000"
    networks:
      - internal_network
    volumes:
      - ./Thread:/path/in/container/to/store/data

  sender:
    build:
      context: ./Sender
    ports:
      - "8080:80"
    networks:
      - internal_network
    volumes:
      - ./Sender:/var/www/html 

  apache:
    image: php:7.4-apache
    volumes:
      - ./apache/apache.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "3001:80"
    depends_on:
      - api
    networks:
      - internal_network

  db:
    build:
      context: ./DB
    networks:
      - internal_network
    volumes:
      - db_data:/path/in/container/to/store/data

networks:
  internal_network:

volumes:
  db_data:
