version: '3.9'

services:
  api:
    build:
      context: ./API
    ports:
      - "3000:3000"
    networks:
      - internal_network

  apache:
    image: php:7.4-apache
    volumes:
      - ./apache/apache.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - internal_network

  db:
    build:
      context: ./DB
    networks:
      - internal_network
    volumes:
      - db_data:/path/in/container/to/store/data

  thread:
    build:
      context: ./Thread
    ports:
      - "80:80"
    networks:
      - internal_network
    volumes:
      - thread_data:/path/in/container/to/store/data

  sender:
    build:
      context: ./Sender
    ports:
      - "8080:8080"
    networks:
      - internal_network

networks:
  internal_network:

volumes:
  db_data:
  thread_data:
