# Partir de ngix 
# Utiliser une image NGINX comme base
FROM nginx

# Set the working directory in the container
WORKDIR /var/www/html

# Copier les configurations NGINX dans le conteneur
COPY dist /usr/share/nginx/html

COPY . .

# Exposez le port sur lequel le service écoute
EXPOSE 80

# Lancer npm run build avant docker compose build !!!!!


# # Partir de ngix 
# # Utiliser une image NGINX comme base
# FROM nginx

# WORKDIR /app

# # Copier tout sauf node_modules
# COPY ./src ./public ./dist ./

# RUN npm install

# RUN npm run build

# # Copier les configurations NGINX dans le conteneur
# RUN cp /app/dist /usr/share/nginx/html

# # Exposez le port sur lequel le service écoute
# EXPOSE 8080

