# Utilisez une image de base appropriée
FROM node:14

# Répertoire de travail dans le conteneur
WORKDIR /app

# Copiez les fichiers nécessaires dans le conteneur
COPY *.php ./

# Exposez le port sur lequel le service écoute
EXPOSE 3000

# Commande pour démarrer le service
CMD ["php", "-S", "localhost:3000", ".\src\app.php"]
