name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: forum_db
          MYSQL_USER: db_user
          MYSQL_PASSWORD: db_password

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and run Docker services
      run: |
        docker-compose up --build -d

    - name: Run PHPUnit tests
      run: |
        chmod +x vendor/bin/phpunit API/tests/ApiTest.php

    - name: Stop and remove Docker services
      run: |
        docker-compose down

    ##### Partie Docker Swarm #####

    # Connexion to manager ec2
    - name: Connect to EC2 manager
      run: |
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@ec2-51-44-5-56.eu-west-3.compute.amazonaws.com

    # Utilisation de la private key
    - name: Use private key
      run: |
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} docker swarm join --token SWMTKN-1-41clbviu1r57oe0jacjl0xfdxdd1uzubodz2w8uc1xn9ihkcej-0b5gcqqg5hzthnx2dwqi45y0j 172.31.47.13:2377